site_name: LIBXSTREAM
site_author: Hans Pabst
copyright: Copyright (c) Intel Corporation, LIBXSTREAM <a href="http://libxstream.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library and accelerator backend.
repo_url: https://github.com/hfp/libxstream/
edit_uri: edit/main/documentation
site_url: https://libxstream.readthedocs.io/
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 3
    title: None
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- md_in_html
- admonition
- attr_list
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

extra:
  collapsed_nav:
    - "Samples"
    - "Tests"
    - "More"

plugins:
  - search

hooks:
  - .theme/hook.py

nav:
- Overview: index.md
- Presentations: libxstream_present.md
- Domains:
  - "OpenCL": libxstream_opencl.md
  - "DBCSR": libxstream_dbcsr.md
  - "CP2K": libxstream_cp2k.md
- Samples:
  - Stencil: samples/libxstream_stencil.md
  - Ozaki: samples/libxstream_ozaki.md
  - SMM: samples/libxstream_smm.md
- Tests:
  - Predict: tests/predict.md
- More:
  - Development: libxstream_scripts.md
  - LIBXS: libxstream_libxs.md
