site_name: LIBXSTREAM
site_author: Hans Pabst
copyright: Copyright (c) Intel Corporation, LIBXSTREAM <a href="http://libxstream.readthedocs.io/LICENSE/">Contributors</a>.
site_description: Library for extra small auxiliary functions and specialized operations.
repo_url: https://github.com/hfp/libxstream/
edit_uri: edit/main/documentation
site_url: https://libxstream.readthedocs.io/
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 3
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

nav:
- Overview: index.md
- Ozaki Getting Started:
  - Howto: libxstream_ozaki.md
  - Details: samples/libxstream_ozaki.md
- LIBXSTREAM Domains:
  - "OpenCL": libxstream_opencl.md
  - "DBCSR": libxstream_dbcsr.md
  - "CP2K": libxstream_cp2k.md
- LIBXS:
  - Reference: libxstream_libxs.md
- Example Code:
  - Ozaki: samples/libxstream_ozaki.md
  - SMM: samples/libxstream_smm.md
- Development:
  - Scripts: libxstream_scripts.md
- About:
  - License: LICENSE.md
