/******************************************************************************
* Copyright (c) 2009-2026 Hans Pabst                                          *
* Copyright (c) 2009-2026 Intel Corporation                                   *
* This file is part of the LIBXSTREAM library.                                *
*                                                                             *
* For information on the license, see the LICENSE file.                       *
* Further information: https://github.com/hfp/libxstream/                     *
* SPDX-License-Identifier: BSD-3-Clause                                       *
******************************************************************************/
#include <libxstream/libxstream_opencl.h>
#include <libxs/libxs_str.h>
#include <libxs/libxs.h>
/* Header smm_kernels.h is generated by the build system using tool_opencl.sh */
#include "smm_kernels.h"

/**
 * Shows which entry a device name selects (libxstream_opencl_device_match), by
 * default among the built-in entries that tuned parameters and prediction models
 * come from, otherwise among the names given after the device.
 *
 * One line per entry: its index, "id" if it carries the device's UID, the word
 * score, the edit distance, and its name; the selection follows on its own line.
 * With exactly one name given, the raw and cleaned comparison precede the table.
 */


int main(int argc, char* argv[])
{
  int result = EXIT_SUCCESS;
  /* a UID without "[0x...]" is a hash, whose software CRC needs LIBXS' tables */
  libxs_init();
  if (2 <= argc) {
    const char* const device = argv[1];
#if defined(OPENCL_KERNELS_DEVICES)
    const char* const* const names = (2 < argc) ? (const char* const*)(argv + 2) : OPENCL_KERNELS_DEVICES;
    const int nnames = (2 < argc) ? (argc - 2)
                                  : (int)(sizeof(OPENCL_KERNELS_DEVICES) / sizeof(*OPENCL_KERNELS_DEVICES));
#else
    const char* const* const names = (const char* const*)(argv + 2);
    const int nnames = argc - 2;
#endif
    if (0 < nnames) {
      char devclean[LIBXSTREAM_BUFFERSIZE], clean[LIBXSTREAM_BUFFERSIZE];
      unsigned int uid = 0;
      int i = 0, selected;
      if (3 == argc) { /* one name: how the comparison sees the raw and the cleaned pair */
        char a[LIBXSTREAM_BUFFERSIZE], b[LIBXSTREAM_BUFFERSIZE];
        int count = 0, order = 0, n, dist;
        LIBXS_SNPRINTF(a, sizeof(a), "%s", argv[1]);
        LIBXS_SNPRINTF(b, sizeof(b), "%s", argv[2]);
        n = libxs_strimatch(a, b, NULL, &count);
        dist = libxs_strisimilar(a, b, NULL, LIBXS_STRISIMILAR_DEFAULT, &order);
        if (0 != n && 0 != count) {
          fprintf(stdout, "strimatch: match=%d count=%d score=%.4f\n", n, count, (double)n / count);
        }
        else {
          fprintf(stdout, "strimatch: no match\n");
        }
        fprintf(stdout, "strisimilar: distance=%d order=%d\n", dist, order);
        libxstream_opencl_device_name_cleanup(a);
        libxstream_opencl_device_name_cleanup(b);
        fprintf(stdout, "cleaned: \"%s\" vs \"%s\"\n", a, b);
        count = 0;
        order = 0;
        n = libxs_strimatch(a, b, NULL, &count);
        dist = libxs_strisimilar(a, b, NULL, LIBXS_STRISIMILAR_DEFAULT, &order);
        if (0 != n && 0 != count) {
          fprintf(stdout, "strimatch (cleaned): match=%d count=%d score=%.4f\n", n, count, (double)n / count);
        }
        else {
          fprintf(stdout, "strimatch (cleaned): no match\n");
        }
        fprintf(stdout, "strisimilar (cleaned): distance=%d order=%d\n", dist, order);
      }
      libxstream_opencl_device_uid(NULL /*device*/, device, &uid);
      LIBXS_SNPRINTF(devclean, sizeof(devclean), "%s", device);
      libxstream_opencl_device_name_cleanup(devclean);
      for (; i < nnames; ++i) {
        unsigned int id = 0;
        int count = 0, n, dist;
        LIBXS_SNPRINTF(clean, sizeof(clean), "%s", names[i]);
        libxstream_opencl_device_name_cleanup(clean);
        n = libxs_strimatch(devclean, clean, NULL, &count);
        dist = libxs_strisimilar(devclean, clean, NULL, LIBXS_STRISIMILAR_DEFAULT, NULL);
        libxstream_opencl_device_uid(NULL /*device*/, names[i], &id);
        fprintf(stdout, "[%i] %s %.4f %i %s\n", i, (0 != uid && uid == id) ? "id" : "--",
          (0 < n && 0 < count) ? (double)n / count : 0.0, dist, names[i]);
      }
      selected = libxstream_opencl_device_match(device, uid, names, nnames);
      if (0 <= selected) fprintf(stdout, "selected: [%i] %s\n", selected, names[selected]);
      else fprintf(stdout, "selected: none\n");
    }
    else {
      fprintf(stderr, "ERROR: no built-in device entries, give names after the device\n");
      result = EXIT_FAILURE;
    }
  }
  else {
    fprintf(stderr, "Usage: %s \"device-name\" [\"entry-name\" ...]\n", argv[0]);
    fprintf(stderr, "       Without entries, the built-in device entries are matched.\n");
    result = EXIT_FAILURE;
  }
  libxs_finalize();
  return result;
}
