/******************************************************************************
* Copyright (c) Intel Corporation - All rights reserved.                      *
* This file is part of the LIBXSTREAM library.                                *
*                                                                             *
* For information on the license, see the LICENSE file.                       *
* Further information: https://github.com/hfp/libxstream/                     *
* SPDX-License-Identifier: BSD-3-Clause                                       *
******************************************************************************/
#if defined(__OPENCL)
#  include "smm_acc_opencl.h"
/* Header smm_kernels.h is generated by the build system using tool_opencl.sh */
#  include "smm_kernels.h"
#  include "acc_bench.h"
#  include <libxs/libxs_predict.h>
#  include <libxs/libxs_str.h>
#  include <ctype.h>

#  if !defined(OPENCL_LIBSMM_KERNELNAME_TRANS)
#    define OPENCL_LIBSMM_KERNELNAME_TRANS "trans"
#  endif
#  if !defined(OPENCL_LIBSMM_KERNELNAME_SMM)
#    define OPENCL_LIBSMM_KERNELNAME_SMM "smm"
#  endif
#  define OPENCL_LIBSMM_SMMENV(KEY) opencl_libsmm_getenv("OPENCL_LIBSMM_SMM", KEY)

#  if defined(OPENCL_KERNELS_PREDICT_MODELS)
OPENCL_KERNELS_PREDICT_INCBIN();
#  endif

#  if defined(__cplusplus)
extern "C" {
#  endif

/* Defined in smm_kernel.c */
extern opencl_libsmm_acc_dbm_launch_fn_t opencl_libsmm_acc_dbm_launch_fn;
/* track initialization status of LIBSMM */
int opencl_libsmm_initialized;
/* registry for dispatch/register of SMM and transpose kernels */
libxs_registry_t* opencl_libsmm_registry;
#  if defined(OPENCL_KERNELS_PREDICT_MODELS)
libxs_predict_t* opencl_libsmm_predict_model;
static int opencl_libsmm_predict_mode; /* -1=disabled, 0=fallback(default), 1=force */
#  endif


int libsmm_acc_init(void) {
#  if defined(_OPENMP)
  /* initialization/finalization is not meant to be thread-safe */
  int result = ((0 == omp_in_parallel() || /*main*/ 0 == omp_get_thread_num()) ? EXIT_SUCCESS : EXIT_FAILURE);
#    pragma omp critical(opencl_libsmm_initialized)
#  else
  int result = EXIT_SUCCESS;
#  endif
  ++opencl_libsmm_initialized;
  /* multiple calls to libsmm_acc_init are not considered as an error */
  if (1 == opencl_libsmm_initialized) {
#  if !defined(__DBCSR_ACC)
    /* DBCSR shall call libxstream_init as well as libsmm_acc_init (since both interfaces are used).
     * Also, libsmm_acc_init may privately call libxstream_init (as it depends on the ACC interface).
     * The implementation of libxstream_init should hence be safe against "over initialization".
     * However, DBCSR only calls libxstream_init (and expects an implicit libsmm_acc_init).
     */
    if (EXIT_SUCCESS == result) result = libxstream_init();
#  endif
    libxs_init();
    if (EXIT_SUCCESS == result) {
      opencl_libsmm_registry = libxs_registry_create();
      if (NULL == opencl_libsmm_registry) result = EXIT_FAILURE;
    }
    if (EXIT_SUCCESS == result) {
      opencl_libsmm_perfest_t perfest;
      char* const env_params = getenv("OPENCL_LIBSMM_SMM_PARAMS"); /* !opencl_libsmm_getenv */
#  if defined(OPENCL_KERNELS_PREDICT_MODELS)
      const char* const env_predict = OPENCL_LIBSMM_SMMENV("PREDICT");
      opencl_libsmm_predict_mode = (NULL == env_predict || '\0' == *env_predict) ? 0 : atoi(env_predict);
#  endif
      LIBXS_MEMZERO(&perfest);
      if ((NULL == env_params || '0' != *env_params)
#  if defined(OPENCL_KERNELS_PREDICT_MODELS)
          && 0 >= opencl_libsmm_predict_mode
#  endif
      )
      {
        char buffer[LIBXSTREAM_BUFFERSIZE], bufname[LIBXSTREAM_BUFFERSIZE];
#  if defined(OPENCL_KERNELS_DEVICES)
        const int ndevices_params = (int)(sizeof(OPENCL_KERNELS_DEVICES) / sizeof(*OPENCL_KERNELS_DEVICES));
#  endif
        opencl_libsmm_smm_t config;
        opencl_libsmm_smmkey_t key, key_direct;
        int key_direct_skip = 0, ntuned = 0;
        if (NULL != env_params && '\0' != *env_params) { /* filename */
          FILE* const file = fopen(env_params, "r");
          if (NULL != file) {
            /* consume first line, check for device entry, and skip CSV header */
            if (NULL != fgets(buffer, LIBXSTREAM_BUFFERSIZE, file)) {
              char* const device = (NULL != libxs_stristr(buffer, "device") ? bufname : NULL);
              opencl_libsmm_perfest_t* const gflops = (NULL != libxs_stristr(buffer, "gflops") ? &perfest : NULL);
              while (NULL != fgets(buffer, LIBXSTREAM_BUFFERSIZE, file)) { /* read params from CSV-file */
                if (EXIT_SUCCESS == opencl_libsmm_read_smm_params(buffer, &key, &config, gflops, device, NULL /*key_ok*/)) {
                  opencl_libsmm_smm_t* config_init;
                  libxstream_opencl_config.devmatch = 0; /* disable device-match */
                  key.devuid = 0;
                  config_init = (opencl_libsmm_smm_t*)libxs_registry_get(
                    opencl_libsmm_registry, &key, sizeof(key), libxs_registry_lock(opencl_libsmm_registry));
                  if (NULL == config_init) {
                    if (NULL == libxs_registry_set(opencl_libsmm_registry, &key, sizeof(key), &config, sizeof(config),
                                  libxs_registry_lock(opencl_libsmm_registry)))
                    {
                      result = EXIT_FAILURE;
                      break;
                    }
                    else {
                      ++ntuned;
                    }
                  }
                  else if (config_init->gflops < config.gflops) { /* update */
                    memcpy(config_init, &config, sizeof(config));
                  }
                }
                else {
                  if (0 != libxstream_opencl_config.verbosity) {
                    fprintf(stderr, "WARN LIBSMM: failed to load tuned parameters from CSV-file!\n");
                  }
                  break; /* invalid entry */
                }
              }
            }
            else { /* invalid header */
              result = EXIT_FAILURE;
            }
            fclose(file);
          }
          else if (EXIT_SUCCESS == opencl_libsmm_read_smm_params(
                                     env_params, &key_direct, &config, NULL /*perfest*/, NULL /*device*/, &key_direct_skip))
          {
            /* try OPENCL_LIBSMM_SMM_PARAMS as string of kernel parameters (not device-specific) */
            LIBXS_ASSERT(0 == key_direct.devuid && 0 != key_direct_skip);
            if (NULL != libxs_registry_set(opencl_libsmm_registry, &key_direct, sizeof(key_direct), &config, sizeof(config),
                          libxs_registry_lock(opencl_libsmm_registry)))
            {
              libxstream_opencl_config.devmatch = 0; /* disable device-match */
              ntuned = 1;
            }
            else {
              result = EXIT_FAILURE;
            }
          }
          else if (0 == key_direct_skip && 0 != libxstream_opencl_config.verbosity) { /* soft-error */
            fprintf(stderr, "WARN LIBSMM: failed to open parameter file!\n");
          }
        }
#  if defined(OPENCL_KERNELS_PARAMS_SMM) && defined(OPENCL_KERNELS_DEVICES)
        if (EXIT_SUCCESS == result && (0 == ntuned || 0 != key_direct_skip)) {
          const char *line = OPENCL_KERNELS_PARAMS_SMM, *next;
          const cl_device_id device_id = libxstream_opencl_config.devices[libxstream_opencl_config.device_id];
          unsigned int default_uid = libxstream_opencl_config.device.uid;
          int active_match = -1;
          if (EXIT_SUCCESS == libxstream_opencl_device_name(device_id, bufname, LIBXSTREAM_BUFFERSIZE, NULL /*platform*/,
                                0 /*platform_maxlen*/,
                                /*cleanup*/ 1))
          {
            /* determine best-matching parameters based on name of device */
            int i = 0, count = 0;
            double best = 0;
            if (1 >= libxstream_opencl_config.devmatch) {
              libxstream_opencl_device_uid(device_id, bufname, &default_uid);
            }
            for (; i < ndevices_params; ++i) {
              const int n = libxs_strimatch(bufname, OPENCL_KERNELS_DEVICES[i], NULL, &count);
              if (0 != n && 0 != count) {
                const double score = (double)n / count;
                unsigned int uid;
                if (best < score ||
                    (EXIT_SUCCESS == libxstream_opencl_device_uid(NULL /*device*/, OPENCL_KERNELS_DEVICES[i], &uid) &&
                      uid == default_uid))
                {
                  active_match = i;
                  best = score;
                }
              }
            }
          }
          do {
            next = strchr(line, '\n');
            if (NULL != next && next < (line + LIBXSTREAM_BUFFERSIZE)) {
              const int len = next - line;
              memcpy(buffer, line, len);
              buffer[len] = '\0';
              if (EXIT_SUCCESS == opencl_libsmm_read_smm_params(/* read params from embedded params */
                                    buffer, &key, &config, &perfest, bufname /*consume name/id*/, NULL /*key_ok*/))
              {
                if (0 == key_direct_skip || 0 != memcmp(&key_direct, &key, (const char*)&key.k - (const char*)&key)) {
                  opencl_libsmm_smm_t* config_init;
                  const int i = atoi(bufname);
                  if (0 >= ndevices_params || 0 == libxstream_opencl_config.devmatch || 0 > i || ndevices_params <= i ||
                      EXIT_SUCCESS != libxstream_opencl_device_uid(NULL /*device*/, OPENCL_KERNELS_DEVICES[i], &key.devuid))
                  {
                    key.devuid = 0;
                  }
                  config_init = (opencl_libsmm_smm_t*)libxs_registry_get(
                    opencl_libsmm_registry, &key, sizeof(key), libxs_registry_lock(opencl_libsmm_registry)); /* duplicate? */
                  if (NULL == config_init) {
                    if (NULL != libxs_registry_set(opencl_libsmm_registry, &key, sizeof(key), &config, sizeof(config),
                                  libxs_registry_lock(opencl_libsmm_registry)))
                      ++ntuned;
                    else { /* failed to register */
                      result = EXIT_FAILURE;
                      break;
                    }
                  }
                  else if (config_init->gflops < config.gflops) { /* update */
                    memcpy(config_init, &config, sizeof(config));
                  }
                  if (active_match == i && 0 != default_uid) {
                    key.devuid = default_uid;
                    config_init = (opencl_libsmm_smm_t*)libxs_registry_get(
                      opencl_libsmm_registry, &key, sizeof(key), libxs_registry_lock(opencl_libsmm_registry));
                    if (NULL != config_init || NULL != libxs_registry_set(opencl_libsmm_registry, &key, sizeof(key), &config,
                                                         sizeof(config), libxs_registry_lock(opencl_libsmm_registry)))
                    {
                      static int info = 0;
                      if (0 == info && 0 == libxs_nrank() && 0 != libxstream_opencl_config.verbosity &&
                          EXIT_SUCCESS == libxstream_opencl_device_name(device_id, bufname, LIBXSTREAM_BUFFERSIZE,
                                            NULL /*platform*/, 0 /*platform_maxlen*/, /*cleanup*/ 0))
                      {
                        LIBXS_ASSERT(i < ndevices_params);
                        if (default_uid != key.devuid) {
                          fprintf(/* print best-matching device */
                            stderr, "INFO ACC/LIBSMM: PARAMS of \"%s\" used for \"%s\"\n", OPENCL_KERNELS_DEVICES[i], bufname);
                        }
                        else {
                          fprintf(
                            stderr, "INFO ACC/LIBSMM: PARAMS of \"%s\" used to instantiate kernels\n", OPENCL_KERNELS_DEVICES[i]);
                        }
                        info = 1;
                      }
                    }
                  }
                }
              }
              else {
                if (0 != libxstream_opencl_config.verbosity) {
                  fprintf(stderr, "WARN LIBSMM: failed to load embedded parameters!\n");
                }
                break;
              }
              line = ++next;
            }
          } while (NULL != next);
        }
#  endif
#  if defined(OPENCL_KERNELS_DEVICES)
        if (EXIT_SUCCESS == result && 0 != ntuned && 0 == libxs_nrank() &&
            (2 <= libxstream_opencl_config.verbosity || 0 > libxstream_opencl_config.verbosity))
        {
          fprintf(stderr, "INFO ACC/LIBSMM: PARAMS in %i set%s loaded targeting ", ntuned, 1 != ntuned ? "s" : "");
          if (0 != libxstream_opencl_config.devmatch) {
            fprintf(stderr, "%i device%s\n", ndevices_params, 1 != ndevices_params ? "s" : "");
            if (3 <= libxstream_opencl_config.verbosity || 0 > libxstream_opencl_config.verbosity) {
              unsigned int i = 0;
              for (; i < LIBXS_CAST_UINT(ndevices_params); ++i) {
                fprintf(stderr, "INFO ACC/LIBSMM: PARAMS -> \"%s\"\n", OPENCL_KERNELS_DEVICES[i]);
              }
            }
          }
          else {
            fprintf(stderr, "any device\n");
          }
        }
#  endif
      }
#  if defined(OPENCL_KERNELS_PREDICT_MODELS) && defined(OPENCL_KERNELS_DEVICES)
      if (EXIT_SUCCESS == result && NULL == opencl_libsmm_predict_model && 0 <= opencl_libsmm_predict_mode) {
        char bufname[LIBXSTREAM_BUFFERSIZE];
        const opencl_kernels_predict_entry_t* entry;
        const opencl_kernels_predict_entry_t* best = NULL;
        const int ndevices_predict = (int)(sizeof(OPENCL_KERNELS_DEVICES) / sizeof(*OPENCL_KERNELS_DEVICES));
        int predict_match = -1;
        if (EXIT_SUCCESS == libxstream_opencl_device_name(libxstream_opencl_config.devices[libxstream_opencl_config.device_id],
                              bufname, LIBXSTREAM_BUFFERSIZE, NULL, 0, 1))
        {
          int i = 0, count = 0;
          double best_score = 0;
          for (; i < ndevices_predict; ++i) {
            const int n = libxs_strimatch(bufname, OPENCL_KERNELS_DEVICES[i], NULL, &count);
            if (0 != n && 0 != count) {
              const double score = (double)n / count;
              if (best_score < score) {
                predict_match = i;
                best_score = score;
              }
            }
          }
        }
        if (0 <= predict_match) {
          for (entry = OPENCL_KERNELS_PREDICT_MODELS; NULL != entry->data; ++entry) {
            if (entry->device_id == predict_match) {
              best = entry;
              break;
            }
          }
        }
        if (NULL == best) {
          for (entry = OPENCL_KERNELS_PREDICT_MODELS; NULL != entry->data; ++entry) {
            if (0 <= entry->device_id) {
              best = entry;
              break;
            }
          }
        }
        if (NULL != best) {
          opencl_libsmm_predict_model = libxs_predict_load(best->data, (size_t)(best->data_end - best->data));
          if (NULL != opencl_libsmm_predict_model && opencl_libsmm_predict_mode > 1
            && 0 == ((opencl_libsmm_predict_mode - 1)
              & ~(LIBXS_PREDICT_INTERPOLATE | LIBXS_PREDICT_CLASSIFY | LIBXS_PREDICT_TEMPORAL)))
          {
            libxs_predict_set_mode(opencl_libsmm_predict_model, opencl_libsmm_predict_mode - 1);
          }
          if (NULL != opencl_libsmm_predict_model && 0 == libxs_nrank() &&
              (2 <= libxstream_opencl_config.verbosity || 0 > libxstream_opencl_config.verbosity))
          {
            libxs_predict_query_t qinfo;
            LIBXS_MEMZERO(&qinfo);
            libxs_predict_query(opencl_libsmm_predict_model, &qinfo);
            fprintf(stderr, "INFO ACC/LIBSMM: PREDICT model loaded (%d entries, %d clusters, %.1fx)\n", qinfo.nentries,
              qinfo.nclusters, qinfo.compression);
          }
        }
      }
#  endif
    }
  }
  return result;
}


int libsmm_acc_finalize(void) {
  /* Routine libsmm_acc_init is called in master thread inside of parallel region
   * However, libsmm_acc_finalize is indirectly called (libxstream_finalize)
   * inside of a parallel region (not just the master thread).
   */
#  if defined(_OPENMP)
  /* initialization/finalization is not meant to be thread-safe */
  int result = ((0 == omp_in_parallel() || /*main*/ 0 == omp_get_thread_num()) ? EXIT_SUCCESS : EXIT_FAILURE);
#    pragma omp critical(opencl_libsmm_initialized)
#  else
  int result = EXIT_SUCCESS;
#  endif
  --opencl_libsmm_initialized;
  /* multiple calls to libsmm_acc_finalize are not considered as an error */
  if (0 == opencl_libsmm_initialized) {
    char fname[LIBXSTREAM_MAXSTRLEN];
    size_t cursor = 0;
    const void* regentry = libxs_registry_begin(opencl_libsmm_registry, NULL /*key*/, &cursor);
    for (; NULL != regentry; regentry = libxs_registry_next(opencl_libsmm_registry, NULL /*key*/, &cursor)) {
      /* opencl_libsmm_trans_t/opencl_libsmm_smm_t carry cl_kernel as 1st data member */
      cl_kernel kernel = *(const cl_kernel*)regentry;
      if (NULL == kernel) kernel = ((const opencl_libsmm_smm_t*)regentry)->kernel[1];
      if (NULL != kernel) { /* only consider user-entry if clGetKernelInfo succeeded */
        int result_entry = clGetKernelInfo(kernel, CL_KERNEL_FUNCTION_NAME, sizeof(fname), fname, NULL);
        if (EXIT_SUCCESS == result_entry) {
          if (NULL != strstr(fname, OPENCL_LIBSMM_KERNELNAME_TRANS)) { /* trans-kernel */
            result_entry = clReleaseKernel(kernel);
          }
          else if (NULL != strstr(fname, OPENCL_LIBSMM_KERNELNAME_SMM)) { /* SMM-kernel */
            result_entry = clReleaseKernel(kernel);
            if (EXIT_SUCCESS == result_entry && kernel != ((const opencl_libsmm_smm_t*)regentry)->kernel[1]) {
              kernel = ((const opencl_libsmm_smm_t*)regentry)->kernel[1]; /* release 2nd kernel */
              if (NULL != kernel) result_entry = clReleaseKernel(kernel);
            }
          }
          if (EXIT_SUCCESS != result_entry) result = result_entry;
        }
      }
    }
    libxs_registry_destroy(opencl_libsmm_registry);
    opencl_libsmm_registry = NULL;
#  if defined(OPENCL_KERNELS_PREDICT_MODELS)
    libxs_predict_destroy(opencl_libsmm_predict_model);
    opencl_libsmm_predict_model = NULL;
#  endif
#  if !defined(__DBCSR_ACC)
    /* DBCSR shall call libxstream_init as well as libsmm_acc_init (since both interfaces are used).
     * Also, libsmm_acc_init may privately call libxstream_init (as it depends on the ACC interface).
     * The implementation of libxstream_init should hence be safe against "over initialization".
     * However, DBCSR only calls libxstream_init (and expects an implicit libsmm_acc_init).
     */
    if (EXIT_SUCCESS == result) result = libxstream_finalize();
#  endif
    libxs_finalize();
  }
  /* libxstream_finalize is not called since it can be used independently */
  return result;
}


libxstream_bool_t libsmm_acc_is_thread_safe(void) {
  /* match DBCSR's threading level */
#  if defined(_OPENMP)
  return 1;
#  else
  return 0;
#  endif
}


const char* opencl_libsmm_getenv(const char domain[], const char key[]) {
  char buffer[LIBXSTREAM_BUFFERSIZE];
  const size_t keylen = strlen(key);
  const char* result = NULL;
  int nchar;
  if (2 != keylen) {
    nchar = LIBXS_SNPRINTF(buffer, sizeof(buffer), "%s_%s", domain, key);
    if (0 < nchar && (int)sizeof(buffer) > nchar) result = getenv(buffer);
  }
  else {
    nchar = LIBXS_SNPRINTF(buffer, sizeof(buffer), "%s_PARAMS", domain);
    if (0 < nchar && (int)sizeof(buffer) > nchar) result = getenv(buffer);
    if (NULL == result || '0' != *result) {
      nchar = LIBXS_SNPRINTF(buffer, sizeof(buffer), "%s_%s", domain, key);
      result = (0 < nchar && (int)sizeof(buffer) > nchar) ? getenv(buffer) : NULL;
    }
    else {
      result = NULL;
    }
  }
  return result;
}


libxstream_bool_t libsmm_acc_process_suitable(
  libxstream_bool_t def_mnk, libsmm_acc_data_t datatype, int stack_size, int m_max, int n_max, int k_max, int max_kernel_dim) {
  libxstream_bool_t result = 0; /* false */
  const int mn = m_max * n_max;
  if (0 < mn && 0 < k_max && 0 < stack_size &&
      0 != def_mnk /*homogeneous*/
      /* allow k_max to exceed max_kernel_dim, TODO: BLAS for large kernels (m,n) */
      && mn <= (max_kernel_dim * max_kernel_dim))
  {
    switch (datatype) {
#  if defined(OPENCL_LIBSMM_F64)
      case dbcsr_type_real_8: {
        result = 1; /* true */
      } break;
#  endif
#  if defined(OPENCL_LIBSMM_F32)
      case dbcsr_type_real_4: {
        result = 1; /* true */
      } break;
#  endif
      default: LIBXS_ASSERT(/*false*/ 0 == result);
    }
  }
  if ((/*false*/ 0 == result) && (2 <= libxstream_opencl_config.verbosity || 0 > libxstream_opencl_config.verbosity)) {
    opencl_libsmm_smmkey_t key;
    opencl_libsmm_smm_t dummy;
    key.type = datatype;
    key.m = m_max;
    key.n = n_max;
    key.k = k_max; /* initialize key */
    LIBXS_MEMZERO(&dummy); /* mute warnings about potentially uninitialized data */
    LIBXS_STDIO_ACQUIRE();
    fprintf(stderr, "INFO ACC/LIBSMM: SMM-kernel ");
    opencl_libsmm_write_smm_params(stderr, 1 /*only_key*/, &key, NULL /*config*/, NULL /*delim*/, NULL /*begin*/, NULL /*close*/);
    fprintf(stderr, "=");
    opencl_libsmm_write_smm_params(stderr, 1 /*only_key*/, &key, &dummy, NULL /*delim*/, NULL /*begin*/, NULL /*close*/);
    fprintf(stderr, " ss=%i", stack_size);
    if (mn <= (max_kernel_dim * max_kernel_dim)) {
      fprintf(stderr, 0 != def_mnk ? " is ignored\n" : " is inhomogeneous\n");
    }
    else {
      fprintf(stderr, " is too large\n");
    }
    LIBXS_STDIO_RELEASE();
  }
  return result;
}

int libsmm_acc_process(const int* host_param_stack, const int* dev_param_stack, int stack_size, libsmm_acc_data_t datatype,
  const void* dev_a_data, const void* dev_b_data, void* dev_c_data, int m_max, int n_max, int k_max, int max_kernel_dim,
  libxstream_bool_t def_mnk, void* stream, void* c_stream) {
  int result = EXIT_SUCCESS;
#  if defined(OPENCL_LIBSMM_PFORMAT) && (0 < OPENCL_LIBSMM_PFORMAT)
  LIBXS_ASSERT(LIBXS_MAX(LIBXS_MAX(m_max, n_max), k_max) < (1 << (OPENCL_LIBSMM_PFORMAT - 1)));
  if (dbcsr_type_real_8 == datatype && 0 != def_mnk && NULL != opencl_libsmm_acc_dbm_launch_fn) {
    result = opencl_libsmm_acc_dbm_launch_fn(stream, 1.0 /*alpha*/, stack_size,
      m_max | (n_max << OPENCL_LIBSMM_PFORMAT) | (k_max << (OPENCL_LIBSMM_PFORMAT * 2)), host_param_stack, dev_param_stack,
      (const double*)dev_a_data, (const double*)dev_b_data, (double*)dev_c_data);
  }
  else
#  endif
  {
    result = opencl_libsmm_acc_process(host_param_stack, dev_param_stack, stack_size, datatype, dev_a_data, dev_b_data, dev_c_data,
      m_max, n_max, k_max, max_kernel_dim, def_mnk, stream, c_stream, 0 /*param_format*/, NULL /*event*/);
  }
  return result;
}


int c_calculate_norms(const double* mat, int nblks, const int* offsets, const int* nelems, float* norms, void* stream_ptr) {
  LIBXS_UNUSED(mat);
  LIBXS_UNUSED(nblks);
  LIBXS_UNUSED(offsets);
  LIBXS_UNUSED(nelems);
  LIBXS_UNUSED(norms);
  LIBXS_UNUSED(stream_ptr);
  return -1;
}

#  if defined(__cplusplus)
}
#  endif

#endif /*__OPENCL*/
