get_filename_component(_libxstream_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

set(_libxstream_suffixes_save "${CMAKE_FIND_LIBRARY_SUFFIXES}")
if(DEFINED BUILD_SHARED_LIBS AND NOT BUILD_SHARED_LIBS)
  set(CMAKE_FIND_LIBRARY_SUFFIXES .a)
endif()
find_library(LIBXSTREAM_LIBRARY NAMES xstream HINTS "${_libxstream_prefix}/lib" NO_DEFAULT_PATH)
if(NOT LIBXSTREAM_LIBRARY)
  set(CMAKE_FIND_LIBRARY_SUFFIXES "${_libxstream_suffixes_save}")
  find_library(LIBXSTREAM_LIBRARY NAMES xstream HINTS "${_libxstream_prefix}/lib" NO_DEFAULT_PATH)
endif()
set(CMAKE_FIND_LIBRARY_SUFFIXES "${_libxstream_suffixes_save}")
unset(_libxstream_suffixes_save)
find_path(LIBXSTREAM_INCLUDE_DIR NAMES libxstream/libxstream.h HINTS "${_libxstream_prefix}/include" "${_libxstream_prefix}" NO_DEFAULT_PATH)

if(LIBXSTREAM_LIBRARY AND LIBXSTREAM_INCLUDE_DIR)
  if(NOT TARGET libxstream::libxstream)
    find_package(libxs CONFIG QUIET
      HINTS "${_libxstream_prefix}")
    find_package(OpenCL QUIET)
    find_package(OpenMP QUIET COMPONENTS C)
    add_library(libxstream::libxstream UNKNOWN IMPORTED)
    set_target_properties(libxstream::libxstream PROPERTIES
      IMPORTED_LOCATION "${LIBXSTREAM_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${LIBXSTREAM_INCLUDE_DIR}")
    if(TARGET libxs::libxs)
      set_property(TARGET libxstream::libxstream APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES libxs::libxs)
    endif()
    if(TARGET OpenCL::OpenCL)
      set_property(TARGET libxstream::libxstream APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES OpenCL::OpenCL)
    endif()
    if(TARGET OpenMP::OpenMP_C)
      set_property(TARGET libxstream::libxstream APPEND PROPERTY
        INTERFACE_LINK_LIBRARIES OpenMP::OpenMP_C)
    endif()
  else()
    set_property(TARGET libxstream::libxstream PROPERTY
      IMPORTED_LOCATION "${LIBXSTREAM_LIBRARY}")
  endif()
endif()

if(EXISTS "${_libxstream_prefix}/include/libxstream/opencl")
  set(LIBXSTREAM_INCLUDE_DIRS "${_libxstream_prefix}/include/libxstream")
elseif(EXISTS "${_libxstream_prefix}/libxstream/opencl")
  set(LIBXSTREAM_INCLUDE_DIRS "${_libxstream_prefix}/libxstream")
else()
  set(LIBXSTREAM_INCLUDE_DIRS "${_libxstream_prefix}/include")
endif()
if(EXISTS "${_libxstream_prefix}/share/libxstream/samples/smm/smm_acc.c")
  set(LIBXSTREAM_OPENCL_SCRIPT "${_libxstream_prefix}/share/libxstream/scripts/tool_opencl.sh")
  set(LIBXSTREAM_SMM_DIR "${_libxstream_prefix}/share/libxstream/samples/smm")
else()
  set(LIBXSTREAM_OPENCL_SCRIPT "${_libxstream_prefix}/scripts/tool_opencl.sh")
  set(LIBXSTREAM_SMM_DIR "${_libxstream_prefix}/samples/smm")
endif()
set(LIBXSTREAM_SMM_ACC_SOURCE "${LIBXSTREAM_SMM_DIR}/smm_acc.c")

if(NOT LIBXSTREAM_LIBRARY)
  find_library(LIBXSTREAM_LIBRARY NAMES xstream HINTS "${_libxstream_prefix}/lib" NO_DEFAULT_PATH)
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(libxstream DEFAULT_MSG LIBXSTREAM_LIBRARY)
unset(_libxstream_prefix)
