name: GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: [DBG=0, DBG=1 PEDANTIC=2]
    steps:
    - uses: actions/checkout@v4

    - name: Install Requirements
      run: sudo apt install -y opencl-c-headers ocl-icd-dev

    - name: Setup Dependencies
      run: |
        git clone --depth 1 https://github.com/hfp/libxs.git ${{ github.workspace }}/../libxs
        echo "LIBXSROOT=${{ github.workspace }}/../libxs" >> $GITHUB_ENV

    - name: Build
      run: make -j $(nproc) ${{ matrix.flags }}
